backend:
  name: github
  repo: pomme-health/pomme-health-website

media_folder: "images/uploads"

collections:
  - label: "Website Settings"
    name: "website-settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Copyright"
            name: "copyright"
            widget: "string"
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Banner"
            name: "heroBanner"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
