backend:
  name: github
  repo: pomme-health/pomme-health-website

media_folder: "images/uploads"

collections:
  - label: "Website Settings"
    name: "website-settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Copyright"
            name: "copyright"
            widget: "string"
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Banner"
            name: "heroBanner"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "buttonText"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
          - label: "Cards Section Title"
            name: "sectionTitle"
            widget: "string"
          - label: "Home Cards"
            name: "homeCards"
            widget: "list"
            fields:
              - label: "Icon"
                name: "icon"
                widget: "image"
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
          - label: "Home Sections"
            name: "homeSections"
            widget: "list"
            fields:
              - label: "Leading Text"
                name: "leadingText"
                widget: "string"
              - label: "Title"
                name: "mainSectionHeader"
                widget: "string"
              - label: "Text"
                name: "mainSectionText"
                widget: "string"
              - label: "Button Text"
                name: "sectionButton"
                widget: "string"
              - label: "Button Link"
                name: "mainSectionLink"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
          - label: "Get in Touch"
            name: "getInTouch"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
      - label: "POMMe Platform"
        name: "pomme-platform"
        file: "_data/platform.yml"
        fields:
          - label: "Platform Sections"
            name: "platform"
            widget: "list"
            fields:
              - label: "Title"
                name: "mainSectionHeader"
                widget: "string"
              - label: "Text"
                name: "mainSectionText"
                widget: "string"
              - label: "Button Text"
                name: "sectionButton"
                widget: "string"
              - label: "Button Link"
                name: "mainSectionLink"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
      - label: "About"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: "History"
            name: "history"
            widget: "object"
            fields:
              - label: "History Title"
                name: "historyTitle"
                widget: "string"
              - label: "History Text"
                name: "historyText"
                widget: "string"
          - label: "Mission"
            name: "mission"
            widget: "object"
            fields:
              - label: "Mission Title"
                name: "aboutHeader"
                widget: "string"
              - label: "Mission Text"
                name: "aboutText"
                widget: "string"

      - label: "Comprehensive"
        name: "comprehensive"
        file: comprehensive.md
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
      - label: "Collaborative"
        name: "collaborative"
        file: collaborative.md
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
      - label: "Continuous"
        name: "continuous"
        file: continuous.md
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
      - label: "Contact"
        name: "contactPage"
        file: "_data/contact.yml"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Text"
            name: "text"
            widget: "string"
  - label: "Blog Posts"
    name: "blog-posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "blog"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "desc"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
